Update Dockerfile
odpi/egeria-ui pull request #468
Opened 2022-10-31 11:37 UTC by sarbull

Signed-off-by: Sirbu Nicolae-Cezar <sirbunicolaecezar@gmail.com>

2022-10-31 11:38 UTC, sarbull commented
@planetf1 let's continue the discussion here

2022-10-31 12:25 UTC, sarbull commented
@planetf1 i updated the PR here

2022-10-31 14:23 UTC, planetf1 requested changes

2022-10-31 14:27 UTC, planetf1 requested changes

2022-10-31 14:27 UTC, planetf1 commented on Dockerfile
> +FROM nginx:1.19.0
Alternatively could try https://github.com/odpi/egeria-ui/issues/289 - that would be the desired end-state, in particular for runtime

2022-10-31 14:29 UTC, planetf1 commented on Dockerfile
> +ARG version=4.0.2
No I think you are right to use a fixed version!

2022-10-31 14:32 UTC, planetf1 commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/nginx-120
1.71 is the latest stable @sarbull ( https://catalog.redhat.com/software/containers/ubi8/nginx-120/6156abfac739c0a4123a86fd )

2022-11-01 08:35 UTC, sarbull commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/nginx-120
updated

2022-11-01 09:31 UTC, planetf1 approved these changes

2022-11-01 09:32 UTC, merged